name: CI

on:
  push:
    branches: master

  pull_request:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10, 12, 14, 16]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm test
        if: ${{ matrix.node-version != 16 }}
      - run: npm run test:coverage
        if: ${{ matrix.node-version == 16 }}
      - uses: codecov/codecov-action@v2
        if: ${{ matrix.node-version == 16 }}
